[package]
name = "eips"
version = "0.1.0"
authors = ["taylor.fish <contact@taylor.fish>"]
edition = "2018"

[features]
no_std = []
allocator_api = []

[dependencies]
tagged-pointer = "0.2"

[dependencies.fixed-bump]
version = "0.1"
features = ["allocator_api"]
