[package]
name = "eips"
version = "0.1.0"
authors = ["taylor.fish <contact@taylor.fish>"]
edition = "2021"

[features]
default = ["std"]
std = []

[dependencies]
allocator-fallback = { path = "../allocator-fallback" }
default-cell = { path = "../default-cell" }
tagged-pointer = "0.2"

[dependencies.fixed-bump]
path = "../fixed-bump"
features = ["allocator-fallback"]

[dependencies.skip-list]
path = "../skip-list"
